import Todoapp from "@/components/Todoapp";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section className="flex justify-center items-center h-screen">
        <Todoapp />
      </section>
    </>
  );
}
